/* {\Tt all.h} for \impcore S295a */
#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include <inttypes.h>
#include <limits.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* type definitions for \impcore 43c */
typedef int32_t Value;
typedef struct Valuelist *Valuelist;     // list of Value
/* type definitions for \impcore 44a */
typedef struct Funclist *Funclist; // list of Func
/* type definitions for \impcore 44e */
typedef struct Valenv *Valenv;
typedef struct Funenv *Funenv;
/* type definitions for \impcore S292c */
typedef struct UnitTestlist *UnitTestlist; // list of UnitTest
/* type definitions for \impcore S292d */
typedef struct Explist *Explist; // list of Exp
/* type definitions for \impcore (generated by a script) */
typedef struct Exp *Exp;
typedef enum { LITERAL, VAR, SET, IFX, WHILEX, BEGIN, APPLY } Expalt;

/* type definitions for \impcore (generated by a script) */
typedef struct Userfun Userfun; 
typedef struct Def *Def;
typedef enum { VAL, EXP, DEFINE } Defalt; 
/* type definitions for \impcore (generated by a script) */
typedef struct XDef *XDef;
typedef enum { DEF, USE, TEST } XDefalt; 
typedef struct UnitTest *UnitTest;
typedef enum { CHECK_EXPECT, CHECK_ASSERT, CHECK_ERROR } UnitTestalt;

/* type definitions for \impcore (generated by a script) */
typedef struct Func Func;
typedef enum { USERDEF, PRIMITIVE } Funcalt; 
/* shared type definitions 43a */
typedef struct Name *Name;
typedef struct Namelist *Namelist;   // list of Name
/* shared type definitions S197a */
typedef struct ParserState *ParserState;
typedef struct ParsingContext *ParsingContext;
/* shared type definitions S197d */
typedef enum ParserResult {
  PARSED,            // some input was parsed without any errors
  INPUT_EXHAUSTED,   // there aren't enough inputs
  INPUT_LEFTOVER,    // there are too many inputs
  BAD_INPUT,         // an input wasn't what it should have been
  STOP_PARSING       // all the inputs have been parsed; it's time to stop
} ParserResult;
/* shared type definitions S197e */
typedef ParserResult (*ShiftFun)(ParserState);
/* shared type definitions S201d */
typedef struct ParserRow *ParserTable;
/* shared type definitions S209a */
enum Sugar {
  CAND, COR,    // short-circuit Boolean operators

  WHILESTAR, DO_WHILE, FOR,     // bonus loop forms

  WHEN, UNLESS,       // single-sided conditionals

  RECORD,             // record-type definition

  COND                // McCarthy's conditional from Lisp

};
/* shared type definitions S165a */
typedef struct Linestream *Linestream;
/* shared type definitions S168c */
typedef struct Parlist *Parlist; /* list of Par */
/* shared type definitions S168d */
typedef struct Parstream *Parstream;
/* shared type definitions S174a */
typedef struct Printbuf *Printbuf;
/* shared type definitions S177a */
/* definition of [[va_list_box]] S177b */
typedef struct va_list_box {
  va_list ap;
} va_list_box;
typedef void Printer(Printbuf output, va_list_box *args);
/* shared type definitions S293a */
typedef struct XDefstream *XDefstream;
/* shared type definitions S293d */
typedef enum Prompts { NOT_PROMPTING, PROMPTING } Prompts;
/* shared type definitions S293f */
typedef enum Echo { NOT_ECHOING, ECHOING } Echo;
/* shared type definitions S293h */
typedef struct Sourceloc *Sourceloc;
/* shared type definitions S294a */
typedef enum ErrorFormat { WITH_LOCATIONS, WITHOUT_LOCATIONS } ErrorFormat;
/* shared type definitions S300e */
typedef enum TestResult { TEST_PASSED, TEST_FAILED } TestResult;
/* shared type definitions (generated by a script) */
typedef struct Par *Par;
typedef enum { ATOM, LIST } Paralt; 

/* structure definitions for \impcore S194b */
struct Component {
    Exp exp;
    Explist exps;
    Name name;
    Namelist names;
};
/* structure definitions for \impcore (generated by a script) */
struct Exp {
    Expalt alt;
    union {
        Value literal;
        Name var;
        struct { Name name; Exp exp; } set;
        struct { Exp cond; Exp truex; Exp falsex; } ifx;
        struct { Exp cond; Exp exp; } whilex;
        Explist begin;
        struct { Name name; Explist actuals; } apply;
    } ;
};

/* structure definitions for \impcore (generated by a script) */
struct Userfun { Namelist formals; Namelist locals; Exp body; };
struct Def {
    Defalt alt;
    union {
        struct { Name name; Exp exp; } val;
        Exp exp;
        struct { Name name; Userfun userfun; } define;
    } ;
};

/* structure definitions for \impcore (generated by a script) */
struct XDef { XDefalt alt; union { Def def; Name use; UnitTest test; } ; };

struct UnitTest {
    UnitTestalt alt;
    union {
        struct { Exp check; Exp expect; } check_expect;
        Exp check_assert;
        Exp check_error;
    } ;
};

/* structure definitions for \impcore (generated by a script) */
struct Func { Funcalt alt; union { Userfun userdef; Name primitive; } ; }; 
/* structure definitions for \impcore (generated by a script) */
struct Parlist {
   Par hd;
   struct Parlist *tl;
};

struct Namelist {
   Name hd;
   struct Namelist *tl;
};

struct Valuelist {
   Value hd;
   struct Valuelist *tl;
};

struct Funclist {
   Func hd;
   struct Funclist *tl;
};

struct UnitTestlist {
   UnitTest hd;
   struct UnitTestlist *tl;
};

struct Explist {
   Exp hd;
   struct Explist *tl;
};

/* shared structure definitions S196b */
#define MAXCOMPS 4 // max # of components in any syntactic form
struct ParserState {
    int nparsed;       // number of components parsed so far
    struct Component components[MAXCOMPS];  // those components
    Parlist input;     // the part of the input not yet parsed

    struct ParsingContext {   // context of this parse
        Par par;       // the original thing being parsed
        struct Sourceloc {
            int line;                // current line number
            const char *sourcename;  // where the line came from
        } *source;
        Name name;     // a keyword, or name of a function being defined
    } context;
};
/* shared structure definitions S201a */
struct ParserRow {
    const char *keyword;
    int code;
    ShiftFun *shifts;  // points to array of shift functions
};
/* shared structure definitions S166a */
struct Linestream {
    char *buf;               // holds the last line read
    int bufsize;             // size of buf

    struct Sourceloc source; // where the last line came from
    FILE *fin;               // non-NULL if filelines
    const char *s;           // non-NULL if stringlines
};
/* shared structure definitions (generated by a script) */
struct Par { Paralt alt; union { Name atom; Parlist list; } ; }; 

/* definition of [[__noreturn]] S295b */
#ifdef __GNUC__
#define __noreturn __attribute__((noreturn))
#else
#define __noreturn
#endif
/* function prototypes for \impcore 44f */
Valenv mkValenv(Namelist vars, Valuelist vals);
Funenv mkFunenv(Namelist vars, Funclist  defs);
/* function prototypes for \impcore 44g */
Value fetchval(Name name, Valenv env);
Func  fetchfun(Name name, Funenv env);
/* function prototypes for \impcore 45a */
bool isvalbound(Name name, Valenv env);
bool isfunbound(Name name, Funenv env);
/* function prototypes for \impcore 45b */
void bindval(Name name, Value val, Valenv env);
void bindfun(Name name, Func  fun, Funenv env);
/* function prototypes for \impcore 45c */
Value eval   (Exp e, Valenv globals, Funenv functions, Valenv formals);
void  evaldef(Def d, Valenv globals, Funenv functions, Echo echo_level);
/* function prototypes for \impcore S293e */
void readevalprint(XDefstream s, Valenv globals, Funenv functions, Echo
                                                                    echo_level);
/* function prototypes for \impcore S296b */
void process_tests(UnitTestlist tests, Valenv globals, Funenv functions);
/* function prototypes for \impcore S300b */
int number_of_good_tests(UnitTestlist tests, Valenv globals, Funenv functions);
/* function prototypes for \impcore S300f */
TestResult test_result(UnitTest t, Valenv globals, Funenv functions);
/* function prototypes for \impcore (generated by a script) */
Exp mkLiteral(Value literal);
Exp mkVar(Name var);
Exp mkSet(Name name, Exp exp);
Exp mkIfx(Exp cond, Exp truex, Exp falsex);
Exp mkWhilex(Exp cond, Exp exp);
Exp mkBegin(Explist begin);
Exp mkApply(Name name, Explist actuals);
struct Exp mkLiteralStruct(Value literal);
struct Exp mkVarStruct(Name var);
struct Exp mkSetStruct(Name name, Exp exp);
struct Exp mkIfxStruct(Exp cond, Exp truex, Exp falsex);
struct Exp mkWhilexStruct(Exp cond, Exp exp);
struct Exp mkBeginStruct(Explist begin);
struct Exp mkApplyStruct(Name name, Explist actuals);
/* function prototypes for \impcore S292a */
Userfun mkUserfun(Namelist formals, Namelist locals, Exp body);
Def mkVal(Name name, Exp exp);
Def mkExp(Exp exp);
Def mkDefine(Name name, Userfun userfun);
struct Def mkValStruct(Name name, Exp exp);
struct Def mkExpStruct(Exp exp);
struct Def mkDefineStruct(Name name, Userfun userfun);
/* function prototypes for \impcore (generated by a script) */
XDef mkDef(Def def);
XDef mkUse(Name use);
XDef mkTest(UnitTest test);
struct XDef mkDefStruct(Def def);
struct XDef mkUseStruct(Name use);
struct XDef mkTestStruct(UnitTest test);
UnitTest mkCheckExpect(Exp check, Exp expect);
UnitTest mkCheckAssert(Exp check_assert);
UnitTest mkCheckError(Exp check_error);
struct UnitTest mkCheckExpectStruct(Exp check, Exp expect);
struct UnitTest mkCheckAssertStruct(Exp check_assert);
struct UnitTest mkCheckErrorStruct(Exp check_error);
/* function prototypes for \impcore 44d */
Func mkUserdef(Userfun userdef);
Func mkPrimitive(Name primitive);
/* function prototypes for \impcore (generated by a script) */
int     lengthPL(Parlist ps);
Par     nthPL   (Parlist ps, unsigned n);
Parlist mkPL    (Par p, Parlist ps);
Parlist popPL   (Parlist ps);
Printer printparlist;

int      lengthNL(Namelist ns);
Name     nthNL   (Namelist ns, unsigned n);
Namelist mkNL    (Name n, Namelist ns);
Namelist popNL   (Namelist ns);
Printer  printnamelist;

int       lengthVL(Valuelist vs);
Value     nthVL   (Valuelist vs, unsigned n);
Valuelist mkVL    (Value v, Valuelist vs);
Valuelist popVL   (Valuelist vs);
Printer   printvaluelist;

int      lengthFL(Funclist fs);
Func     nthFL   (Funclist fs, unsigned n);
Funclist mkFL    (Func f, Funclist fs);
Funclist popFL   (Funclist fs);
Printer  printfunclist;

int          lengthUL(UnitTestlist us);
UnitTest     nthUL   (UnitTestlist us, unsigned n);
UnitTestlist mkUL    (UnitTest u, UnitTestlist us);
UnitTestlist popUL   (UnitTestlist us);
Printer      printunittestlist;

int     lengthEL(Explist es);
Exp     nthEL   (Explist es, unsigned n);
Explist mkEL    (Exp e, Explist es);
Explist popEL   (Explist es);
Printer printexplist;

/* shared function prototypes 43b */
Name strtoname(const char *s);
const char *nametostr(Name x);
/* shared function prototypes 46b */
void print (const char *fmt, ...);  // print to standard output
void fprint(FILE *output, const char *fmt, ...);  // print to given file
/* shared function prototypes 47a */
__noreturn // OMIT
void runerror (const char *fmt, ...);
extern jmp_buf errorjmp;        // longjmp here on error
/* shared function prototypes 47b */
__noreturn // OMIT
void synerror (Sourceloc src, const char *fmt, ...);
/* shared function prototypes 47c */
void checkargc(Exp e, int expected, int actual);
/* shared function prototypes S192a */
Exp  parseexp (Par p, Sourceloc source);
XDef parsexdef(Par p, Sourceloc source);
/* shared function prototypes S192b */
Exp exp_of_atom(Sourceloc loc, Name atom);
/* shared function prototypes S195a */
Exp  reduce_to_exp (int alt, struct Component *components);
XDef reduce_to_xdef(int alt, struct Component *components);
/* shared function prototypes S197c */
struct ParserState mkParserState(Par p, Sourceloc source);
/* shared function prototypes S197f */
ParserResult sExp     (ParserState state);  // shift 1 input into Exp
ParserResult sExps    (ParserState state);  // shift all inputs into Explist
ParserResult sName    (ParserState state);  // shift 1 input into Name
ParserResult sNamelist(ParserState state);  // shift 1 input into Namelist
/* shared function prototypes S198b */
void halfshift(ParserState state); // advance input, check for room in output
/* shared function prototypes S198e */
Explist parseexplist(Parlist p, Sourceloc source);
/* shared function prototypes S199b */
Name parsename(Par p, ParsingContext context);
/* shared function prototypes S200a */
ParserResult stop(ParserState state);
/* shared function prototypes S200c */
ParserResult setcontextname(ParserState state);
/* shared function prototypes S200f */
ParserResult sLocals(ParserState state);
                 // shift locals if [locals x y z ...]
/* shared function prototypes S201c */
void rowparse(struct ParserRow *table, ParserState s);
__noreturn /* OMIT */
void usage_error(int alt, ParserResult r, ParsingContext context);
/* shared function prototypes S202a */
struct ParserRow *tableparse(ParserState state, ParserTable t);
/* shared function prototypes S205b */
ParserResult use_exp_parser(ParserState state);
/* shared function prototypes S208c */
int code_of_name(Name n);
/* shared function prototypes S208d */
void check_exp_duplicates(Sourceloc source, Exp e);
void check_def_duplicates(Sourceloc source, Def d);
/* shared function prototypes S165b */
char *getline_(Linestream r, const char *prompt);
/* shared function prototypes S165c */
Linestream stringlines(const char *stringname, const char *s);
Linestream filelines  (const char *filename,   FILE *fin);
/* shared function prototypes S168e */
Parstream parstream(Linestream lines, Prompts prompts);
Par       getpar   (Parstream r);
Sourceloc parsource(Parstream pars);
/* shared function prototypes S169a */
extern bool read_tick_as_quote;
/* shared function prototypes S174b */
Printbuf printbuf(void);
void freebuf(Printbuf *);
/* shared function prototypes S174c */
void bufput(Printbuf, char);
void bufputs(Printbuf, const char*);
void bufreset(Printbuf);
/* shared function prototypes S174d */
char *bufcopy(Printbuf);
void fwritebuf(Printbuf buf, FILE *output);
/* shared function prototypes S176d */
void print (const char *fmt, ...);                  // print to standard output
void fprint(FILE *output, const char *fmt, ...);    // print to given file
void bprint(Printbuf output, const char *fmt, ...); // print to given buffer
/* shared function prototypes S176e */
void installprinter(unsigned char specifier, Printer *take_and_print);
/* shared function prototypes S177c */
void vbprint(Printbuf output, const char *fmt, va_list_box *box);
/* shared function prototypes S179c */
Printer printpercent, printstring, printdecimal, printchar, printname, 
        printpointer;
/* shared function prototypes S180e */
Printer printpar;
/* shared function prototypes S181a */
typedef enum ErrorMode { NORMAL, TESTING } ErrorMode;
void set_error_mode(ErrorMode mode);
extern jmp_buf testjmp;    // if error occurs during a test, longjmp here
extern Printbuf errorbuf;  // if error occurs during a test, message is here
/* shared function prototypes S184a */
__noreturn // OMIT
void othererror (const char *fmt, ...);
/* shared function prototypes S184d */
Name duplicatename(Namelist names);
/* shared function prototypes S186a */
extern int  checkoverflow(int limit);
extern void reset_overflow_check(void);
/* shared function prototypes S187b */
extern void checkarith(char operation, int32_t n, int32_t m, int precision);
/* shared function prototypes S188a */
void fprint_utf8(FILE *output, unsigned code_point);
void print_utf8 (unsigned u);
/* shared function prototypes S293b */
XDef getxdef(XDefstream xdefs);
/* shared function prototypes S293c */
XDefstream stringxdefs(const char *stringname, const char *input);
XDefstream filexdefs  (const char *filename, FILE *input, Prompts prompts);
/* shared function prototypes S293g */
void installprinter(unsigned char c, Printer *take_and_print);
/* shared function prototypes S294b */
void set_toplevel_error_format(ErrorFormat format);
/* shared function prototypes S300c */
void report_test_results(int npassed, int ntests);
/* shared function prototypes S304d */
Printer printexp, printdef, printvalue, printfun;
/* shared function prototypes (generated by a script) */
Par mkAtom(Name atom);
Par mkList(Parlist list);
struct Par mkAtomStruct(Name atom);
struct Par mkListStruct(Parlist list);

/* macro definitions used in parsing S195d */
#define ANEXP(ALT)  (  0+(ALT))
#define ADEF(ALT)   (100+(ALT))
#define ATEST(ALT)  (200+(ALT))
#define ANXDEF(ALT) (300+(ALT))
#define ALET(ALT)   (400+(ALT))
#define SUGAR(CODE) (500+(CODE))
#define LATER       1000
#define EXERCISE    1001
/* declarations of globals used in lexical analysis and parsing S202e */
extern struct ParserRow exptable[];
extern struct ParserRow xdeftable[];
/* declarations of globals used in lexical analysis and parsing S206b */
extern struct Usage {
    int code;             // codes for form in reduce_to_exp or reduce_to_xdef
    const char *expected; // shows the expected usage of the identified form
} usage_table[];
